services:
  # ===== 인프라 =====
  postgres:
    image: postgres:16
    container_name: lucky-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - lucky-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-lucky} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: lucky-redis
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - lucky-network

  zipkin:
    image: openzipkin/zipkin
    container_name: lucky-zipkin
    ports:
      - "9411:9411"
    networks:
      - lucky-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    container_name: lucky-keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_ADMIN_SECRET: ${KEYCLOAK_ADMIN_SECRET}
      KEYCLOAK_USER_SECRET: ${KEYCLOAK_USER_SECRET}
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false" # 실제 서버 운영시에는 true
      KC_HTTP_ENABLED: "true"
      command: start-dev --import-realm
    volumes:
      - ./keycloak/realm-export-2.json:/opt/keycloak/data/import/realm.json
      - keycloak_data:/opt/keycloak/data # user 데이터 저장
    ports:
      - "9090:8080" #(접속할 때 http://localhost:9090 사용)
    networks:
      - lucky-network

  # ============ eureka-server ==============
  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    container_name: lucky-eureka
    restart: unless-stopped
    ports:
      - "19090:19090"
    networks:
      - lucky-network
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -q http://localhost:19090/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # ============ company-service ==============
  company-service:
    build:
      context: .
      dockerfile: company-service/Dockerfile
    container_name: lucky-company
    ports:
      - "${COMPANY_SERVICE_PORT}:${COMPANY_SERVICE_PORT}"
    environment:
      COMPANY_SERVICE_PORT: ${COMPANY_SERVICE_PORT}
      COMPANY_SERVICE_NAME: ${COMPANY_SERVICE_NAME}
      COMPANY_SERVICE_SCHEMA: ${COMPANY_SERVICE_SCHEMA}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - lucky-network
    depends_on:
      postgres:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    restart: unless-stopped

  # ============ hub-service ==============
  hub-service:
    build:
      context: .
      dockerfile: hub-service/Dockerfile
    container_name: lucky-hub
    ports:
      - "${HUB_SERVICE_PORT}:${HUB_SERVICE_PORT}"
    environment:
      HUB_SERVICE_PORT: ${HUB_SERVICE_PORT}
      HUB_SERVICE_NAME: ${HUB_SERVICE_NAME}
      HUB_SERVICE_SCHEMA: ${HUB_SERVICE_SCHEMA}
      TMAP_API_KEY: ${TMAP_API_KEY}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - lucky-network
    depends_on:
      postgres:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    restart: unless-stopped

  # ============ order-service ==============
  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    container_name: lucky-order
    ports:
      - "${ORDER_SERVICE_PORT}:${ORDER_SERVICE_PORT}"
    environment:
      ORDER_SERVICE_PORT: ${ORDER_SERVICE_PORT}
      ORDER_SERVICE_NAME: ${ORDER_SERVICE_NAME}
      ORDER_SERVICE_SCHEMA: ${ORDER_SERVICE_SCHEMA}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - lucky-network
    depends_on:
      postgres:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    restart: unless-stopped

  # ============ product-service ==============
  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    container_name: lucky-product
    ports:
      - "${PRODUCT_SERVICE_PORT}:${PRODUCT_SERVICE_PORT}"
    environment:
      PRODUCT_SERVICE_PORT: ${PRODUCT_SERVICE_PORT}
      PRODUCT_SERVICE_NAME: ${PRODUCT_SERVICE_NAME}
      PRODUCT_SERVICE_SCHEMA: ${PRODUCT_SERVICE_SCHEMA}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - lucky-network
    depends_on:
      postgres:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    restart: unless-stopped

  # ============ api-gateway ==============
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: lucky-gateway
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    environment:
      GATEWAY_NAME: ${GATEWAY_NAME}
      GATEWAY_PORT: ${GATEWAY_PORT}
      EUREKA_SERVER: lucky-eureka
    env_file:
      - .env
    networks:
      - lucky-network
    depends_on:
      eureka-server:
        condition: service_healthy
    restart: unless-stopped

  # ============ notification-service ==============
  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    container_name: lucky-notification
    ports:
        - "${NOTIFICATION_SERVICE_PORT}:${NOTIFICATION_SERVICE_PORT}"
    environment:
      SLACK_TOKEN: ${SLACK_TOKEN}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      NOTIFICATION_SERVICE_PORT: ${NOTIFICATION_SERVICE_PORT}
      NOTIFICATION_SERVICE_NAME: ${NOTIFICATION_SERVICE_NAME}
      NOTIFICATION_SERVICE_SCHEMA: ${NOTIFICATION_SERVICE_SCHEMA}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - lucky-network
    depends_on:
      postgres:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    restart: unless-stopped

  # ============ user-service ==============
  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: lucky-user
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    environment:
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      USER_SERVICE_NAME: ${USER_SERVICE_NAME}
      USER_SERVICE_SCHEMA: ${USER_SERVICE_SCHEMA}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_SERVER_URL: http://lucky-keycloak:8080
      KEYCLOAK_REALM: lucky
      # 회원가입용 (관리자 권한)
      KEYCLOAK_ADMIN_SECRET: ${KEYCLOAK_ADMIN_SECRET}
      # 로그인용 (일반 클라이언트 권한)
      KEYCLOAK_USER_SECRET: ${KEYCLOAK_USER_SECRET}
    env_file:
      - .env
    networks:
      - lucky-network
    depends_on:
      eureka-server:
        condition: service_healthy
    restart: unless-stopped

networks:
  lucky-network:
    driver: bridge

volumes:
  postgres_data:
  keycloak_data: