#application-local.yaml

server:
  port: 19300

spring:
  application:
    name: company-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:lucky_logistics}?currentSchema=${COMPANY_SERVICE_SCHEMA:company_schema}
    username: ${POSTGRES_USER:lucky}
    password: ${POSTGRES_PASSWORD:lucky7777}
  jpa:
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      resourceserver:
        jwt:
          # 로컬에서 Keycloak은 localhost:9090으로 접근
          issuer-uri: http://localhost:9090/realms/lucky
          jwk-set-uri: http://localhost:9090/realms/lucky/protocol/openid-connect/certs

# 로깅 설정
logging:
  level:
    com.sparta.lucky.company: DEBUG # 본 패키지
    org.hibernate.SQL: DEBUG # SQL 쿼리 출력
    org.hibernate.jdbc.bind: TRACE # 바인딩 파라미터

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka
  instance:
    # Docker 컨테이너(Gateway)가 호스트 머신에서 실행 중인 company-service에 접근하기 위한 설정
    hostname: host.docker.internal
    prefer-ip-address: false