########################
#        Spring        #
########################
spring.application.name=delivery-service

# Database
spring.datasource.url = jdbc:postgresql://localhost:5432/lucky-db
spring.datasource.username = lucky
spring.datasource.password = ${POSTGRES_PASSWORD}
spring.datasource.driver-class-name = org.postgresql.Driver

# sql init
spring.sql.init.mode=never

########################
#          JPA         #
########################
# ??? ?? ? DB ??? ?? ??
spring.jpa.hibernate.ddl-auto = update
# ???? SQL? ??? ??
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

########################
#        Eureka        #
########################
eureka.client.service-url.defaultZone = http://localhost:19090/eureka/
eureka.client.register-with-eureka = true
eureka.client.fetch-registry=true

eureka.instance.hostname=delivery-service
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90
