### ================================================================
### Keycloak 인증 - 테스트용 토큰 발급
###
### 사용법:
###   1. 환경 드롭다운에서 'gateway' 선택
###   2. 아래 요청 순서대로 실행 → accessToken이 global 변수에 자동 저장
###   3. order-crud.http, order-internal.http 에서 {{accessToken}} 으로 사용
### ================================================================

### [1] MASTER 토큰 발급
POST {{keycloakUrl}}/realms/lucky/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=lucky-client&username=master-user&password={{masterPassword}}

> {%

    client.test("MASTER 토큰 발급 성공", function() {
        client.assert(response.status === 200, "status 200 expected");
        client.assert(response.body.access_token !== undefined, "access_token 반환 필요");
    });
    if (response.status === 200 && response.body.access_token) {
        client.global.set("accessToken", response.body.access_token);
    }
%}

### [2] COMPANY_MANAGER 토큰 발급
POST {{keycloakUrl}}/realms/lucky/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=lucky-client&username=company-manager-user&password={{masterPassword}}

> {%

    client.test("COMPANY_MANAGER 토큰 발급 성공", function() {
        client.assert(response.status === 200, "status 200 expected");
        client.assert(response.body.access_token !== undefined, "access_token 반환 필요");
    });
    if (response.status === 200 && response.body.access_token) {
        client.global.set("companyManagerToken", response.body.access_token);
    }
%}

### [3] HUB_MANAGER 토큰 발급
POST {{keycloakUrl}}/realms/lucky/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=lucky-client&username=hub-manager-user&password={{masterPassword}}

> {%

    client.test("HUB_MANAGER 토큰 발급 성공", function() {
        client.assert(response.status === 200, "status 200 expected");
        client.assert(response.body.access_token !== undefined, "access_token 반환 필요");
    });
    if (response.status === 200 && response.body.access_token) {
        client.global.set("hubManagerToken", response.body.access_token);
    }
%}
